### ISSUE TITLE
Question about survey

### ISSUE THREAD

**Issue by samschott** [Exahilosys/wrapio#1]
@Exahilosys, apologies for abusing this issue tracker to contact you.

I have been looking for something similar to https://github.com/AlecAivazis/survey in Python, I even considered writing it myself. Then I discovered [survey](https://pypi.org/project/survey/0.0.0/#description) on PyPI.

Compared to the many alternatives out there ([questionary](https://github.com/tmbo/questionary), [bullet](https://github.com/bchao1/bullet), etc), your solution is a lot cleaner and better structured. Despite the lack of doc strings, it's easy to understand. It also does not depend on `prompt_toolkit`, which makes it a comparatively light-weight package.

Is the code eventually going to land on GitHub? And how safe would it be to already use some of it in production? I know its a 0.0.0 version...

**Comment by Exahilosys** [comment]
Hey @SamSchott, no worries about the issue tracker. I just published the final version of the library [here](https://github.com/Exahilosys/survey)! It's fully documented internally, and I'm working on getting it on readthedocs as well. Thanks for showing interest; closing this now, cheers!

**Comment by samschott** [comment]
Nice, thanks!
