### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by coxackie** [Exahilosys/wrapio#2]
Trying to build, I get:
```
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    github_version_parts = github_version.split('/')
AttributeError: 'NoneType' object has no attribute 'split'
```
any ideas?

**Comment by Exahilosys** [comment]
Yeap! It's because you're attempting to build directly from the Github repository. Using the release assets should work. Let me know if it doesn't.

**Comment by Exahilosys** [comment]
I just confirm that it doesn't actually, work. My bad, working on a fix asap.
